### ISSUE TITLE
CompressionError should implement Error

### ISSUE THREAD

**Issue by Eoghanmc22** [adamkewley/libdeflater#14]
CompressionError should implement std's error trait.

**Comment by adamkewley** [comment]
Thanks for this report @Eoghanmc22 . The `Error` trait was added like so:

https://github.com/adamkewley/libdeflater/pull/15/files

And merged in the PR #15. After merging, I published the fix in 0.7.4:

https://crates.io/crates/libdeflater/0.7.4

So you should be able to update your downstream codebase to use `libdeflater 0.7.4` to take advantage of the fix
