### ISSUE TITLE
Feature request: Support compression level 0

### ISSUE THREAD

**Issue by wjv** [adamkewley/libdeflater#21]
libdeflate now [supports compression level 0](https://github.com/ebiggers/libdeflate/commit/4c92394eaa8769e1d832c7719d4fbe7a94ac3c42); it would be great if libdeflater can be updated to support this as well!

I have not done extensive testing, but it would seem simply setting `MIN_COMPRESSION_LVL` to `0` in [`CompressionLvl::new()`](https://github.com/adamkewley/libdeflater/blob/e6b8d58315c7533e926e6e559dff6e9d361ed39a/src/lib.rs#L300) does the trick.

This may sound academic, but it does have real-world use. For instance, in bioinformatics research we often store genetic sequence and alignment data in the [BAM format](https://samtools.github.io/hts-specs/SAMv1.pdf), where data blocks are compressed with deflate by definition. When building pipelines out of tools that read and write BAM format, it is most efficient to use uncompressed files (i.e. compression level 0).

(Thanks to @jch-13 for helping me find the cause of this issue.)

**Comment by adamkewley** [comment]
Agreed that it should just handle it - I'll fix it and push a relevant release

**Comment by adamkewley** [comment]
@wjv  , thanks for writing this up :) - I believe [b299056](https://github.com/adamkewley/libdeflater/commit/b29905601ae11880d8af71c3ab39fe4138b56891) fixes this issue - the API should now accept `0` as a compression level

I published the change as `0.9.0`, which downstream should be able to pull in and test

**Comment by jch-13** [comment]
Thank you! If I'm not mistaken, the new compression level is not yet included in the iterator returned by `CompressionLvl::iter()`: https://github.com/adamkewley/libdeflater/blob/master/src/lib.rs#L326

**Comment by adamkewley** [comment]
@jch-13 you're right - how stupid of me to hard-code the level in the code (I was relying on `rg`ing the symbols)

I'll fix that and ship it as `0.10.0`

**Comment by adamkewley** [comment]
Ok, so `0.10.0` *should* return the correct iterator now. [dcc4924](https://github.com/adamkewley/libdeflater/commit/dcc49246f20466c0461f8e35aba21595e655162a) patches out the hard-coded compression levels that were being used in that part of the codebase - great spot @jch-13 !

The release is available on Cargo. I'll also poke the downstream noodles issue with this information.
