### ISSUE TITLE
Update libdelater-sys to 1.15 which should be quite a bit faster.

### ISSUE THREAD

**Issue by ghuls** [adamkewley/libdeflater#24]
Update libdelater-sys to 1.15 which should be quite a bit faster.

<h2 dir="auto"><a id="user-content-version-115" class="anchor" aria-hidden="true" href="https://github.com/ebiggers/libdeflate/blob/master/NEWS.md#version-115"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a>Version 1.15</h2>
<ul dir="auto">
<li>
<p dir="auto">libdeflate now uses CMake instead of a plain Makefile.</p>
</li>
<li>
<p dir="auto">Improved MSVC support.  Enabled most architecture-specific code with MSVC,
fixed building with clang in MSVC compatibility mode, and other improvements.</p>
</li>
<li>
<p dir="auto">When libdeflate is built with MinGW, the static library and import library are
now named using the MinGW convention (<code>*.a</code> and <code>*.dll.a</code>) instead of the
Visual Studio convention.  This affects the official Windows binaries.</p>
</li>
</ul>
<h2 dir="auto"><a id="user-content-version-114" class="anchor" aria-hidden="true" href="https://github.com/ebiggers/libdeflate/blob/master/NEWS.md#version-114"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a></h2><h2 dir="auto">Version 1.14</h2>
<p dir="auto">Significantly improved decompression performance on all platforms.  Examples
include (measuring DEFLATE only):</p>

Platform | Speedup over v1.13
-- | --
x86_64 (Intel Comet Lake), gcc | 1.287x
x86_64 (Intel Comet Lake), clang | 1.437x
x86_64 (Intel Ice Lake), gcc | 1.332x
x86_64 (Intel Ice Lake), clang | 1.296x
x86_64 (Intel Sandy Bridge), gcc | 1.162x
x86_64 (Intel Sandy Bridge), clang | 1.092x
x86_64 (AMD Zen 2), gcc | 1.263x
x86_64 (AMD Zen 2), clang | 1.259x
i386 (Intel Comet Lake), gcc | 1.570x
i386 (Intel Comet Lake), clang | 1.344x
arm64 (Apple M1), clang | 1.306x
arm64 (Cortex-A76), clang | 1.355x
arm64 (Cortex-A55), clang | 1.190x
arm32 (Cortex-A76), clang | 1.665x
arm32 (Cortex-A55), clang | 1.283x

<p dir="auto">Thanks to Dougall Johnson (<a href="https://dougallj.wordpress.com/" rel="nofollow">https://dougallj.wordpress.com/</a>) for ideas for many
of the improvements.</p>
<h2 dir="auto"><a id="user-content-version-113" class="anchor" aria-hidden="true" href="https://github.com/ebiggers/libdeflate/blob/master/NEWS.md#version-113"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a></h2><h2 dir="auto">Version 1.13</h2>
<ul dir="auto">
<li>
<p dir="auto">Changed the 32-bit Windows build of the library to use the default calling
convention (cdecl) instead of stdcall, reverting a change from libdeflate 1.4.</p>
</li>
<li>
<p dir="auto">Fixed a couple macOS compatibility issues with the gzip program.</p>
</li>
</ul>
<h2 dir="auto"><a id="user-content-version-112" class="anchor" aria-hidden="true" href="https://github.com/ebiggers/libdeflate/blob/master/NEWS.md#version-112"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a></h2><h2 dir="auto">Version 1.12</h2>
<p dir="auto">This release focuses on improving the performance of the CRC-32 and Adler-32
checksum algorithms on x86 and ARM (both 32-bit and 64-bit).</p>
<ul dir="auto">
<li>
<p dir="auto">Build updates:</p>
<ul dir="auto">
<li>
<p dir="auto">Fixed building libdeflate on Apple platforms.</p>
</li>
<li>
<p dir="auto">For Visual Studio builds, Visual Studio 2015 or later is now required.</p>
</li>
</ul>
</li>
<li>
<p dir="auto">CRC-32 algorithm updates:</p>
<ul dir="auto">
<li>
<p dir="auto">Improved CRC-32 performance on short inputs on x86 and ARM.</p>
</li>
<li>
<p dir="auto">Improved CRC-32 performance on Apple Silicon Macs by using a 12-way pmull
implementation.   Performance on large inputs on M1 is now about 67 GB/s,
compared to 8 GB/s before, or 31 GB/s with the Apple-provided zlib.</p>
</li>
<li>
<p dir="auto">Improved CRC-32 performance on some other ARM CPUs by reworking the code so
that multiple crc32 instructions can be issued in parallel.</p>
</li>
<li>
<p dir="auto">Improved CRC-32 performance on some x86 CPUs by increasing the stride length
of the pclmul implementation.</p>
</li>
</ul>
</li>
<li>
<p dir="auto">Adler-32 algorithm updates:</p>
<ul dir="auto">
<li>
<p dir="auto">Improved Adler-32 performance on some x86 CPUs by optimizing the AVX-2
implementation.  E.g., performance on Zen 1 improved from 19 to 30 GB/s, and
on Ice Lake from 35 to 41 GB/s (if the AVX-512 implementation is excluded).</p>
</li>
<li>
<p dir="auto">Removed the AVX-512 implementation of Adler-32 to avoid CPU frequency
downclocking, and because the AVX-2 implementation was made faster.</p>
</li>
<li>
<p dir="auto">Improved Adler-32 performance on some ARM CPUs by optimizing the NEON
implementation.  E.g., Apple M1 improved from about 36 to 52 GB/s.</p>
</li>
</ul>
</li>
</ul>

**Comment by TPS** [comment]
Indeed, going further to v1.17 has a fix for https://github.com/ebiggers/libdeflate/issues/241, which would solve https://github.com/shssoichiro/oxipng/issues/444.

**Comment by adamkewley** [comment]
`0.12.0` has just been published:

- https://crates.io/crates/libdeflater

It's based on `libdeflate:v1.17`, which should give a nice performance uplift

Thanks for reporting this - sorry it's slow: I have many projects going on in parallel etc!

**Comment by TPS** [comment]
@adamkewley Thanks very much! 🙇🏾‍♂️

@ghuls Close `Completed` FTW?

**Comment by adamkewley** [comment]
I also re-ran the benchmarks (oh god, why did I write the processing script in ruby). Overall, the changes between `libdeflate` and `flate2` vary depending on input data shape (see c224f31).

I'm assuming that the absolute timings are much better because I've had maybe 2 PC upgrades, compiler upgrades, etc. since they were last ran.
