### ISSUE TITLE
Upgrade to libdeflate 1.18

### ISSUE THREAD

**Issue by ebiggers** [adamkewley/libdeflater#27]
Please stay up to date with the latest version of libdeflate so that people don't run into issues that have already been fixed.  Thanks!

**Comment by adamkewley** [comment]
Thanks for notifying me @ebiggers

`0.14.0` now uses `libdeflate` v1.18, it has been published to Crates.io:

- https://crates.io/crates/libdeflater

I'll try to keep up-to-date in future, but I don't tend to pay enough attention to GitHub's notification wall thing ☹️
