### ISSUE TITLE
Upgrade to libdeflate 1.19

### ISSUE THREAD

**Issue by andrews05** [adamkewley/libdeflater#28]
There's been a new release of libdeflate, would be great to see an update here soon.

P.S. Thanks heaps for maintaining this 🙂

**Comment by adamkewley** [comment]
Thanks for the update!

I'll try sorting it out later today

**Comment by adamkewley** [comment]
Published as `1.19.0` to here and crates.io:

- https://crates.io/crates/libdeflater

The versioning scheme of this project was also updated to match `libdeflate`, so that it's easier for API users to figure out which version these downstream bindings are bound to.

**Comment by andrews05** [comment]
Nice, thank you! Matching versions is also a big help.
