### ISSUE TITLE
Update to libdeflate 1.21

### ISSUE THREAD

**Issue by magicmaaaaan** [adamkewley/libdeflater#36]
libdeflate 1.21 was released Aug 4, 2024: https://github.com/ebiggers/libdeflate/releases/tag/v1.21

Thank you @adamkewley and contributors for maintaining this library!

**Comment by adamkewley** [comment]
Thanks for pointing this out @magicmaaaaan 

@musicinmybrain has taken the honor of bumping the relevant submodules etc. to 1.21 in this repo (see #37). This has now been published to crates.io:

- https://crates.io/crates/libdeflater/1.21.0
- https://crates.io/crates/libdeflate-sys/1.21.0
